### PR TITLE
Fix rewards landing page

### LINKED ISSUE #4131: Error: GraphQL error: Unexpected error value: { message: "Can not fetch invite code for user: 0xB7967466...
Sentry Issue: [ORIGIN-DAPP-10G](https://sentry.io/organizations/origin-protocol/issues/1384782980/?referrer=github_integration)

```
Error: GraphQL error: Unexpected error value: { message: "Can not fetch invite code for user: 0xB79674662F0CF829A65c308921A47eB4B8A09AdC", locations: [[Object]], path: ["inviteCode"], extensions: { code: "INTERNAL_SERVER_ERROR", exception: [Object] } }
  at new t (/app.f34d1c38.js:180:38109)
  at t.getCurrentResult (/app.f34d1c38.js:180:39716)
  at t.getQueryResult (/app.f34d1c38.js:211:47048)
  at t.a.getExecuteResult (/app.f34d1c38.js:211:42181)
  at t.execute (/app.f34d1c38.js:211:43125)
...
(44 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by shahthepro**
Should fix #4131 

When users click on "Sign Up" in the rewards landing page, they are redirected to `/onboard` only if they are not signed in.

After the sign in and do email and profile attestations, they are taken back to `/welcome` landing page.

### Checklist:

- [ ] Test your work and double-check to confirm that you didn't break anything
- [ ] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation
- [ ] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)

### CODE REVIEW

**Comment by micahalcorn** [comment]
How about just skipping `/welcome` completely? I think that's what @franckc and I would vote for. We should leave it in the code and make sure that it's functional because I'm sure there are still a bunch of links pointing to it. But if a user goes to the new website version, I don't see any reason to go through the old `/welcome`. It has a bit more information on it, but we can expand the new one, if necessary. 😐

**Comment by micahalcorn** [comment]
To state that a different way, I think it's more important to **fix** `/welcome` (if possible) than to route to it. 🙃

**Comment by shahthepro** [comment]
@micahalcorn I just added a new page, that stores the referral token to localStorage and redirects to onboarding. This PR for website https://github.com/OriginProtocol/origin-website/pull/460/files should be deployed after this gets deployed to prod.

**Comment by mikeshultz** [comment]
Did I not already fix #4131 with #4132?  Doesn't look like it's reappared in Sentry and it was reported as working again after deployment.

File: dapps/marketplace/src/pages/ReferralRedirect.js [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+import UserActivationLink from 'components/UserActivationLink'
+
+const localStorageKey = 'growth_invite_code'
+
+const ReferralRedirect = ({ match }) => {
+  const inviteCode = get(match, 'params.inviteCode')
+  const [redirect, setRedirect] = useState(false)
+
+  useEffect(() => {
+    if (inviteCode && inviteCode.length === 11) {
```
Comment (mikeshultz) [inline dapps/marketplace/src/pages/ReferralRedirect.js]: This isn't accurate.  It appears invite code can be 7-11 characters, according to our prod DB.

CC @franckc

File: dapps/marketplace/src/pages/growth/WithEnrolmentModal.js [hunk 2]
```diff
@@ -94,15 +102,19 @@ function withEnrolmentModal(WrappedComponent) {
...
+
       if (mobileDevice() !== null && !rewardsOnMobileEnabled) {
         this.setState({
           open: true,
           stage: 'NotSupportedOnMobile'
         })
-      } else if (!walletPresent) {
+      } else if (!isLoggedIn) {
+        const { pathname, search } = this.props.location
+        sessionStore.set('getStartedRedirect', { pathname, search })
```
Comment (mikeshultz) [inline dapps/marketplace/src/pages/growth/WithEnrolmentModal.js]: Might want to check if this is already set.  I think this is being utilized by mobile to send users to `/campaigns`.

File: dapps/marketplace/src/pages/ReferralRedirect.js (hunk 1 above)
Comment (franckc) [reply dapps/marketplace/src/pages/ReferralRedirect.js]: Yeah, it's kinda funky but looks like the invite code can be between 7 to 11 characters!
Here is the code that generates those invite codes: https://github.com/OriginProtocol/origin/blob/master/infra/growth/src/resources/authentication.js#L204

Comment (shahthepro) [reply dapps/marketplace/src/pages/ReferralRedirect.js]: Thanks @mikeshultz. Will update it.

**Comment by shahthepro** [comment]
@mikeshultz 
> Did I not already fix #4131 with #4132? Doesn't look like it's reappared in Sentry and it was reported as working again after deployment.

The user still get a "failed to enroll" message, if they are not signed in. This PR redirects them to onboarding so that they can sign in before enrolling.

> This is not a critiism on this PR, but on dapp onboarding as a whole: I'd recommend we take a re-look at this whole section again some point. There's perhaps too many paths that can be taken through dapp onboarding that makes this all extremely convoluted.

Yep, agreed. Would be good to do that
