### PR TITLE
Partner referral bug fixes and Growth authorization

### LINKED ISSUE #3358: Unnecessary Messaging Enabled Screen
When going through web-based onboarding in our app, I was presented with a "Messaging Enabled" screen with a green checkmark that referred to "2 of 2 MetaMask messages" having been signed. Of course, I didn't knowingly sign anything, particularly using MetaMask. We should not display this step if the user is in our app. And the wallet vendor should be detected instead of just referring to MetaMask. 🦊

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

### LINKED ISSUE #4092: Under-the-hood rewards signing
When a user of our app signs up for Origin Rewards, there should be no prompt to sign the statement using the wallet. It should be sufficient for the user to check the box in the webview agreeing to the terms and then we should sign without requesting explicit confirmation. 📝

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

### PR DESCRIPTION
**Pull request by shahthepro**
- [x] Remove signing and use authToken (from @origin/auth-client) for authorization on Growth package - Closes #4092 
  - The `authToken` that is generated by `@origin/growth` package and is inserted into DB, is still present and possibly won't removed because of backward compatibility.
  - Removes the need to sign a message for enrolling in Growth Rewards. Needs auth token from `@origin/auth-server` instead.
- [x] Fix the following in partner referral flow
  - The box next to the copy button should have the entire link in it rather than just the referral code.
  - That is now the wrong URL. It should be https://originprotocol.com/referral/2a12e11b94e.
  - Partner screen screen should either be skipped if there is no referral code or if the user is referred by a user (and not partner).
- [x] Fix #3358
  - Redirects the user to the next onboarding screen, after the messaging status has loaded once and there is no sign needed from user.
- [x] Add these screens
  - Show how much the user can earn by joining rewards - https://zpl.io/29zZo8p
  - Show rewards earned (through partner referral) after onboarding - https://zpl.io/bADqZXx
- [ ]

### Before deployment
- [ ] Add `AUTH_PUB_KEY` to EnvKey

### Checklist:

- [x] Test your work and double-check to confirm that you didn't break anything
- [x] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation
- [x] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)
- [x] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)

### CODE REVIEW

File: mobile/src/screens/authentication.js [hunk 1]
```diff
@@ -128,7 +128,8 @@ class AuthenticationScreen extends Component {
                 TouchID.authenticate('Enable access to Origin Marketplace App')
                   .then(() => {
                     this.props.setBiometryType(this.state.biometryType)
-                    if (this.props.settings.referralCode) {
+                    const { referralCode } = this.props.settings
+                    if (referralCode && referralCode.startsWith('op:')) {
```
Comment (mikeshultz) [inline mobile/src/screens/authentication.js]: Good catch!

File: dapps/marketplace/src/pages/growth/Invite.js [hunk 2]
```diff
@@ -52,15 +52,13 @@ class GrowthInvite extends Component {
   }
 
   getInviteCode() {
-    return `${location.protocol}//${location.hostname}/#/welcome/${this.state.inviteCode}`
+    return `https://originprotocol.com/referral/${this.state.inviteCode}`
```
Comment (franckc) [inline dapps/marketplace/src/pages/growth/Invite.js]: We have 2 types of invite codes:
 a. code generated by users. Those point to https://shoporigin.com/#/welcome/<userCode>
 b. code generated for partners. Those point to https://originprotocol.com/referral/<partnerCode>
Won't this change break a. ?

CC @mikeshultz

File: mobile/src/screens/partnerWelcome.js [hunk 3]
```diff
@@ -33,7 +35,9 @@ class PartnerWelcomeScreen extends Component {
     if (this.props.settings.referralCode) {
       // We want to direct the user directly to dapp onboarding
       const url = new URL(this.props.settings.network.dappUrl)
-      url.hash = '/onboard'
+      url.hash =
+        '/onboard?referralCode=' +
+        encodeURIComponent(this.props.settings.referralCode)
```
Comment (mikeshultz) [inline mobile/src/screens/partnerWelcome.js]: This has been tested to work with hash router?  `domain/path#hash?fakeParam=fakevar` is a non-standard URL and those aren't real GET params.

File: dapps/marketplace/src/utils/growthTools.js [hunk 4]
```diff
@@ -209,3 +212,44 @@ export function getContentToShare(action, locale) {
...
+    return null
+  }
+
+  const action = actions.find(
+    action =>
+      action.type ===
+      (referralCode.startsWith('op') ? 'PartnerReferral' : 'Referral')
+  )
+
+  const reward = get(action, 'reward.amount')
```
Comment (mikeshultz) [inline dapps/marketplace/src/utils/growthTools.js]: This is the potential reward, not the reward earned.  This Reward will also show up for users who did not arrive via the referral.  The amount here will likely always be 0 as well since the potential reward is variable.

However, I don't think `rewardEarned` will be set until device registration and the reward is unlocked from the 3 prerequisites(profile, e-mail, etc).

File: dapps/marketplace/src/pages/growth/Invite.js (hunk 2 above)
Comment (mikeshultz) [reply dapps/marketplace/src/pages/growth/Invite.js]: No, it shouldn't break anything.  It just isn't as direct as before.  The originprotocol.com landing page will provide them with a mobile app or desktop link to the URL in (a).

File: dapps/marketplace/src/utils/growthTools.js (hunk 4 above)
Comment (mikeshultz) [reply dapps/marketplace/src/utils/growthTools.js]: Might need to load `campaigns.json` for this information...

File: mobile/android/app/build.gradle [hunk 5]
```diff
@@ -128,7 +128,7 @@ android {
     }
 
     defaultConfig {
-        applicationId "com.origincatcher"
+        applicationId "com.originmarketplace"
```
Comment (tomlinton) [inline mobile/android/app/build.gradle]: The applicationId has to remain as `com.origincatcher` because that is what it was originally published to the Play store as.

Comment (mikeshultz) [reply mobile/android/app/build.gradle]: This is what I was having issues with before as well.

File: mobile/src/screens/partnerWelcome.js (hunk 3 above)
Comment (shahthepro) [reply mobile/src/screens/partnerWelcome.js]: It did work on an Android device.

File: mobile/android/app/build.gradle (hunk 5 above)
Comment (shahthepro) [reply mobile/android/app/build.gradle]: Was having issues when running from CLI. Will revert it if it works fine otherwise.

File: dapps/marketplace/src/utils/growthTools.js (hunk 4 above)
Comment (shahthepro) [reply dapps/marketplace/src/utils/growthTools.js]: Thanks. Will update this.

**Comment by shahthepro** [comment]
@mikeshultz 
> Would be cool if you're going to do giant PRs to elaborate in the description. "Fixing bugs related to X" doesn't really help much.

Sure, will update the description

File: mobile/android/app/build.gradle (hunk 5 above)
Comment (tomlinton) [reply mobile/android/app/build.gradle]: What were you running? You might need to use the android command as defined in `package.json`.

Comment (shahthepro) [reply mobile/android/app/build.gradle]: @tomlinton Okay, just checked it. Adding the `appId` param works. Have reverted the change. Thanks.

File: mobile/src/screens/partnerWelcome.js (hunk 3 above)
Comment (mikeshultz) [reply mobile/src/screens/partnerWelcome.js]: I'm going to have to take your word for this, but something to keep in mind since this is an invalid URL.

File: dapps/marketplace/src/utils/growthTools.js (hunk 4 above)
Comment (mikeshultz) [reply dapps/marketplace/src/utils/growthTools.js]: Working on a fix for this, but not holding up this PR.
