### PR TITLE
Changes to Attestation

### LINKED ISSUE #2426: OAuthToken and OAuthTokenSecret missing from session for Twitter Attestation
This works fine on local builds but fails on production. No other attestation is affected by this.

IMG_20190602_183733_803

A bug reported by priyankg3 on #bug-reports channel.

### LINKED ISSUE #2436: Expand Attestation fields in GraphQL
Allow extra data about attestations to be returned from GraphQL.

See here: https://github.com/OriginProtocol/origin/pull/2406#discussion_r291668320

### PR DESCRIPTION
**Pull request by shahthepro**
Should close #2436 ~~and #2443~~

### Checklist:
- [ ] ~~Store unique id and display name for possible attestations~~ - Moving to a separate PR
- [x] Rewrite GraphQL resolver for attestations
- [x] Fix #2426 
- [x] Change modal designs in DApp
- [x] Test your work and double-check to confirm that you didn't break anything
- [x] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation
- [ ] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)

### CODE REVIEW

**Comment by shahthepro** [comment]
@micahalcorn @nick I'm done with attestation modal redesign for mobile. Will create a separate PR for #2443. We can have this merged if you both are fine with it.

File: dapps/marketplace/src/components/Attestations.js [hunk 1]
```diff
@@ -1,19 +1,46 @@
...
-    {profile.googleVerified && <div className="attestation google" />}
-    {profile.websiteVerified && <div className="attestation website" />}
-    {profile.kakaoVerified && <div className="attestation kakao" />}
-    {profile.githubVerified && <div className="attestation github" />}
-    {profile.linkedinVerified && <div className="attestation linkedin" />}
-    {profile.wechatVerified && <div className="attestation wechat" />}
-  </div>
-)
+const Attestations = ({ profile = {} }) => {
+  const verifiedAttestations = mapVerifiedAttestations(profile)
```
Comment (nick) [inline dapps/marketplace/src/components/Attestations.js]: Can we just loop over the array returned from GraphQL?

File: dapps/marketplace/src/pages/user/Profile.js [hunk 2]
```diff
@@ -131,25 +124,38 @@ class UserProfile extends Component {
...
-        profile.phoneVerified !== prevProfile.phoneVerified ||
-        profile.facebookVerified !== prevProfile.facebookVerified ||
-        profile.googleVerified !== prevProfile.googleVerified ||
-        profile.twitterVerified !== prevProfile.twitterVerified ||
-        profile.airbnbVerified !== prevProfile.airbnbVerified ||
-        profile.websiteVerified !== prevProfile.websiteVerified ||
-        profile.kakaoVerified !== prevProfile.kakaoVerified ||
-        profile.githubVerified !== prevProfile.githubVerified ||
-        profile.linkedinVerified !== prevProfile.linkedinVerified) &&
+        verifiedAttestations.emailVerified !==
```
Comment (nick) [inline dapps/marketplace/src/pages/user/Profile.js]: Can we just check if any keys are different instead of each on individually?

Comment (shahthepro) [reply dapps/marketplace/src/pages/user/Profile.js]: Yep, an array diff of object keys should do. Will update it.

File: dapps/marketplace/src/components/Attestations.js (hunk 1 above)
Comment (shahthepro) [reply dapps/marketplace/src/components/Attestations.js]: I thought about that. But we will end up with lots of `.find`s or for loops. We will be iterating the same array again and again.

Comment (nick) [reply dapps/marketplace/src/components/Attestations.js]: If GraphQL returns them in the correct order, could we say `verfiedAttestations.map(a => <div className={'attestation ${a.id}'} />`

Comment (shahthepro) [reply dapps/marketplace/src/components/Attestations.js]: Those are returned in the order the user added them. But can sort them if you want.

Comment (nick) [reply dapps/marketplace/src/components/Attestations.js]: Yea I think sorting them to keep everything consistent at the GraphQL level makes sense... will cut down on duplication code in the dapp too

Comment (shahthepro) [reply dapps/marketplace/src/components/Attestations.js]: Sure. 👍

File: dapps/marketplace/src/utils/profileTools.js [hunk 3]
```diff
@@ -1,69 +1,77 @@
...
+      return sum
+    }
+
+    switch (provider) {
+      case 'email':
+      case 'phone':
+      case 'facebook':
+      case 'google':
+      case 'twitter':
+        sum += 10
```
Comment (nick) [inline dapps/marketplace/src/utils/profileTools.js]: Lets just add 10% for each attestation but max it out at 100.

File: dapps/marketplace/src/components/AboutParty.js [hunk 4]
```diff
@@ -14,7 +14,35 @@ import Link from 'components/Link'
 
 import query from 'queries/Identity'
 import withOwner from 'hoc/withOwner'
-import { mapVerifiedAttestations } from 'utils/profileTools'
+
+const getVerifiedTooltip = provider => {
+  switch (provider) {
+    case 'email':
```
Comment (nick) [inline dapps/marketplace/src/components/AboutParty.js]: Looks like the brands are translated in profileUtils... maybe we can use that as an fbt param to prevent duplication?

File: dapps/admin/src/pages/users/UserProfile.js [hunk 5]
```diff
@@ -1,6 +1,35 @@
 import React from 'react'
 import { Tag } from '@blueprintjs/core'
-import { mapVerifiedAttestations } from '@origin/marketplace/src/utils/profileTools'
+
+const getDisplayName = provider => {
+  // TBD: Should this be translated?
```
Comment (nick) [inline dapps/admin/src/pages/users/UserProfile.js]: Translations are in profileUtils?

**Comment by nick** [comment]
Going to merge this in now before it gets too big... can you address the feedback in a new PR?

File: dapps/marketplace/src/components/AboutParty.js (hunk 4 above)
Comment (shahthepro) [reply dapps/marketplace/src/components/AboutParty.js]: It looks like you have removed those Tooltip components in your `nick/dapp3` branch. So we may not need this function at all.

File: dapps/marketplace/src/utils/profileTools.js (hunk 3 above)
Comment (shahthepro) [reply dapps/marketplace/src/utils/profileTools.js]: What about first name, last name, avatar and description? Same 10?

File: dapps/marketplace/src/components/AboutParty.js (hunk 4 above)
Comment (nick) [reply dapps/marketplace/src/components/AboutParty.js]: I kept them, just moved to Attestations component

File: dapps/admin/src/pages/users/UserProfile.js (hunk 5 above)
Comment (shahthepro) [reply dapps/admin/src/pages/users/UserProfile.js]: Yes, We can just import that function from marketplace DApp. Just wanted to make sure if we translate things in admin DApp too.

File: dapps/marketplace/src/components/AboutParty.js (hunk 4 above)
Comment (shahthepro) [reply dapps/marketplace/src/components/AboutParty.js]: Got it. Will make this change

File: dapps/admin/src/pages/users/UserProfile.js (hunk 5 above)
Comment (nick) [reply dapps/admin/src/pages/users/UserProfile.js]: Ooh missed this was in admin app. No need to translate there.

File: dapps/marketplace/src/utils/profileTools.js (hunk 3 above)
Comment (nick) [reply dapps/marketplace/src/utils/profileTools.js]: Sure that's fine for now
