### PR TITLE
Bug Fixes

### LINKED ISSUE #3351: [Fractional] Cannot update availability and custom pricing
Came across this when I was trying to add tests for Fractional Listings. Looks like I missed to change it when I worked on the UX of the Calendar component. 

While you can still create/update a Fractional Listing, you cannot set custom pricing or change availability of certain dates.

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

### LINKED ISSUE #3568: Unable To Make Offer
I'm still working on identifying what variables are in play here. At least the following is true:

Buyer: `0x522731a061e896B5Db9dDff9234fB5461A533710`
Seller: `0x96FEb7b6F808dd2BBd09c9E5ccdE77caBd58d019`
Network: Rinkeby
Listing: [4-001-6](https://dapp.staging.originprotocol.com/#/listing/4-001-6) (Housing)
Error: "Cannot read property 'isBefore' of undefined" on `getAvailability`

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

### LINKED ISSUE #3749: Mobile App Installation Reward in the Dashboard
We show [a special banner in the rewards dashboard](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5cfeb22619680119d06b3238) to encourage users to install our mobile app.

- [ ] This should never be displayed when using the app that it references (Origin Marketplace).

Once the reward is earned, we currently show [an updated state](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5cfee556fdc08a5dfeecfea6) within this some element.

- [ ] Remove this.

If the reward is earned, let's [show it in a completed section at the bottom](https://zpl.io/adY7rqL).

- [ ] Do this.

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

### LINKED ISSUE #3958: Gas Price: 0 € or something?
Screenshot_20191112-164834_XRecorder
Screenshot_20191112-164854_XRecorder

Did I pay some ETH or not?
There is a gas price in both cases but the total displayed in € is zero.
So, it's not clear whether I paid or not.

### PR DESCRIPTION
**Pull request by shahthepro**
[Link to test build](https://originprotocol.github.io/test-builds/shah)

- [x] Fix #3568 
- [x] Fix #3749 
- [x] Fix #3351 
- [x] Fix #3958 
- [x] Potential fix for #3970 

### Checklist:

- [ ] Test your work and double-check to confirm that you didn't break anything
- [ ] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation
- [ ] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)

### CODE REVIEW

**Comment by shahthepro** [comment]
@nick @micahalcorn @sparrowDom Merging this now. Will open another PR if you guys have any comments on anything

File: packages/graphql/src/configs/localhost.js [hunk 1]
```diff
@@ -41,8 +41,8 @@ const config = {
   tokens: [],
   messagingAccount: '0xBfDd843382B36FFbAcd00b190de6Cb85ff840118',
   messaging: {
-    messagingNamespace: 'origin',
-    globalKeyServer: 'http://localhost:6647'
+    messagingNamespace: 'origin:dev',
+    globalKeyServer: 'https://messaging.dev.originprotocol.com'
```
Comment (sparrowDom) [inline packages/graphql/src/configs/localhost.js]: Just curious, we do not want the localhost to point to the local running messenger container?

Comment (shahthepro) [reply packages/graphql/src/configs/localhost.js]: For docker, it would still point to localhost:6647. This config is used only when the services are **not** started with docker.

Comment (sparrowDom) [reply packages/graphql/src/configs/localhost.js]: Yeah that makes sense 👍
