### PR TITLE
Tomlinton/t3 feedback

### LINKED ISSUE #3830: Navigation Struggles
If I click "Withdrawal History" in this menu, I get the expected screen. If I then click the back button, I'm routed to [/bonus](https://investor.dev.originprotocol.com/#/bonus) (which happens to be broken). I should return to the dashboard.

Screen Shot 2019-10-31 at 1 56 50 PM

Also, if I accidentally navigate to the root path or type it into my browser (for whatever reason), I think I should be redirected to the dashboard if I have a valid session. Otherwise, I keep having to do my 2FA verification unnecessarily.

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

### LINKED ISSUE #3831: Lockup Validation
I should not be able to submit this form with a non-zero value.

Screen Shot 2019-10-31 at 2 15 08 PM

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

### LINKED ISSUE #3832: Lockup Reward Rounding
We should probably round to max-five-digit precision (and not have trailing 0s) or something to avoid this:

Screen Shot 2019-10-31 at 2 19 00 PM

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

### LINKED ISSUE #3833: Max Lockup
There should be a link encouraging me to lock up all of my available tokens. Similarly, we should validate that the inputted value is not greater than the available balance, which goes hand-in-hand with #3831.

➡️ https://zpl.io/Vk7OqDG

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

### PR DESCRIPTION
**Pull request by tomlinton**
Grab bag of fixes and copy changes for T3.

Closes #3832
Closes #3833 
Closes #3831 
Closes #3830 

### Checklist:

- [x] Test your work and double-check to confirm that you didn't break anything
- [ ] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation
- [ ] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)

### CODE REVIEW

File: infra/token-transfer-client/src/components/LockupCard.js [hunk 1]
```diff
@@ -43,7 +43,11 @@ const LockupCard = ({ lockup }) => {
           ></div>{' '}
           Bonus tokens
           <br />
-          <strong>{Number(lockup.amount).toLocaleString()}</strong>{' '}
+          <strong>
+            {Math.floor(
+              Number((lockup.amount * lockup.bonusRate) / 100)
```
Comment (franckc) [inline infra/token-transfer-client/src/components/LockupCard.js]: 1. Should this use BigNumber for this math. I don't trust JS floating point arithmetic...
2. Why do we floor? Can't the bonus token amount be decimal? For example if the user locks 123 tokens and the bonus rate is 10%, should the user get 12.3 bonus tokens or 12?

Comment (tomlinton) [reply infra/token-transfer-client/src/components/LockupCard.js]: 1. Will change it to BN 👍
2. Because we made the decision to use only integers for token handling everywhere else in T3. For example withdrawals don’t allow decimals, and we round vesting amounts to integers too. We could allow decimals here, probably not too many negatives that I can think of (except not being able to withdraw decimal amounts). What do you think?

Comment (franckc) [reply infra/token-transfer-client/src/components/LockupCard.js]: I'd vote for keeping it simple and rounding to integer.
Though imho we should round up rather than round down-let's not be cheap, it's only a few cents we are talking about...

File: infra/token-transfer-client/src/components/BonusModal.js [hunk 2]
```diff
@@ -128,11 +148,15 @@ class BonusModal extends Component {
...
                   <span style={{ fontSize: '14px' }}>
-                    ({bonusRate}% of lockup)
+                    ({lockupBonusRate}% of lockup)
                   </span>
                 </div>
                 <div className="col-4 text-right">
-                  <strong>{this.state.amount * (bonusRate / 100)}</strong>{' '}
+                  <strong>
+                    {BigNumber(this.state.amount * (lockupBonusRate / 100))
+                      .toFixed(0, 1)
```
Comment (franckc) [inline infra/token-transfer-client/src/components/BonusModal.js]: Per my other comment, I'd use toFixed(0, BigNumber.ROUND_UP).

Same comment for file LockupCard.js
