### PR TITLE
Fix AvailabilityCalculator.js

### LINKED ISSUE #2268: Fractional Usage: can't block some dates
some dates cannot be blocked.
In this specific case only the first available date after a closed date, can't be blocked while the rest works fine.
See it in this unlisted video:
https://youtu.be/b4NcbiFInxw

https://dapp.tripscommunity.com/#/listing/1-000-2543/edit/details/availability
same behavior on https://dapp.originprotocol.com/#/listing/1-000-2543/edit/details/availability

### PR DESCRIPTION
**Pull request by shahthepro**
Closes #2268 

Fixes a bug that prevented changing availability of current date.

### CODE REVIEW

File: packages/graphql/src/utils/AvailabilityCalculator.js [hunk 1]
```diff
@@ -35,10 +35,19 @@ class AvailabilityCalculator {
...
+     * Hack:
+     *
+     * dayjs('2019-05-15') will return date object with value 2019-05-15 00:00:00
+     * dayjs() will return current date with current time. e.g. 2019-05-15 12:30:23
+     * So if startStr is current date, start.isBefore(dayjs()) will always fail
+     * The following line will give date object with the current date at 00:00:00 time
+     */
+    const currentDateIgnoringTime = dayjs(
+      dayjs().format('YYYY-MM-DD')
+    ).subtract(1, 'day') // This subtract is to match it with `start` vairable in L35
```
Comment (nick) [inline packages/graphql/src/utils/AvailabilityCalculator.js]: Can we use `dayjs().startOf('day')`?

**Comment by shahthepro** [comment]
Thanks @nick. Have done it. Do you have comments on this? https://github.com/OriginProtocol/origin/issues/2268#issuecomment-492077635
