### PR TITLE
DApp bug fixes

### LINKED ISSUE #3109: Securing Twitter and Telegram Webhooks
We should only whitelist the following IP addresses for Telegram webhooks for security reasons.
 > All webhook requests from the Bot API are now coming from the subnets 149.154.160.0/20 and 91.108.4.0/22...

Ref: https://core.telegram.org/bots/api#july-29-2019

For Twitter, I did add signature validation to requests. But commented it out, as it failed on staging and production for some reasons. Will have to investigate that now.

### Checklist
- [x] Twitter signature validation
- [ ] Whitelisting IP for Telegram

### LINKED ISSUE #3150: Not Another Listing
It seems that "Other listings by this seller" is always including the listing that I'm currently looking at on a detail page. If the user has no other listings, I think the section should not appear at all.

Screen Shot 2019-08-29 at 9 51 25 PM

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

### LINKED ISSUE #3353: Missing Seller Reviews
@coleman415 seems to have left a review for the buyer on [this purchase](https://shoporigin.com/#/purchases/1-000-3122-3) (perhaps twice?) but [the detail page](https://shoporigin.com/#/purchases/1-000-3122-3) still invites him to do it again. And I'm not seeing any reviews on [the buyer's profile](https://shoporigin.com/#/user/0xB597e5cf8489BA86b8a5b27d56A5F6dA247ca45C/reviews). I'm seeing several "Data" events in the transactions history, so they're probably getting recorded and not surfaced to the DApp for some reason.

This issue appears to apply to all listings/offers as far as I can tell. 🚨

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

### LINKED ISSUE #3480: Remove Blocking Tout in Favor of User Activation
Earlier this year, [we decided to aggressively push for mobile app installations by interrupting users with this modal](https://github.com/OriginProtocol/origin/issues/2091) immediately upon loading the DApp from a non-web3-enabled browser.

This is a terrible experience, so we should treat these users similarly to the way we did prior to releasing Origin Marketplace. We should defer any mention of our app until a user expresses intent to buy or sell, at which point the first step of user activation should feature a prominent CTA for our app. Unlike the days of Origin Wallet, we won't support linking and detecting that the app has been installed. We will just leave the user in this state until she has a web3-enabled browser.

See [this design for mobile](https://zpl.io/VD1yMzl) and [this one for desktop](https://zpl.io/2jWGm4m) 📲

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

### LINKED ISSUE #3503: Backward Verification Navigation
If I reach this screen directly from the rewards campaign "Verifications" screen, I should return to it by clicking the back button rather than navigating to /profile.

IMG_8998

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

### LINKED ISSUE #3619: Unnecessary DAI Conversion
When I attempt to purchase a listing with 0 DAI in my wallet but with sufficient ETH, the DAI conversion is only supposed to come into play when DAI is the only currency accepted by the seller. [This was the decision that we reached last month](https://github.com/OriginProtocol/origin/issues/3419) due to the problems that were being caused by unnecessary DAI swaps. Currently, I'm able to make a DAI-to-ETH offer on [this listing](https://dapp.staging.originprotocol.com/#/listing/4-000-883) even though the seller accepts ETH. If we want to revisit this decision, we need to all be aware of the conclusion and update references to it. Otherwise, this should be fixed.

😐

cc @nick @franckc @shahthepro 

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

### LINKED ISSUE #3686: Website Attestation crashes the app
Seems like clicking on "Download" under Website attestation causes the app to crash on Android.

Screenshot

This was reported by Mila on Discord.

### PR DESCRIPTION
**Pull request by shahthepro**
- [x] Hide website attestation on mobile - Fixes #3686
- [x] Use suggestedToken prop - Fixes #3619
- [x] Fix back link on attestation modal - Fixes #3503
- [x] Update download wallet onboarding screen - Closes #3480 
- [x] Show buyer reviews on DApp - Fixes #3353 
- [x] Add IP whitelist middleware for telegram webhook controller - Closes #3109 
- [x] Hide title when there are no listings - Closes #3150 

### Checklist:

- [x] Test your work and double-check to confirm that you didn't break anything
- [x] [Wrap any new text/strings with `fbt`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#wrapping-text) for translation
- [x] If there are any new/changed strings to translate, [`npm run translate`](https://github.com/OriginProtocol/origin/tree/master/dapps/marketplace/translation#integrating-translations)
- [x] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/origin/tree/master/docs)

### CODE REVIEW

File: dapps/marketplace/src/pages/identity/TelegramAttestation.js [hunk 1]
```diff
@@ -117,15 +143,40 @@ class TelegramAttestation extends Component {
...
+        <TelegramGenerateCode
+          wallet={this.props.wallet}
+          onComplete={result => {
+            if (!result.success) {
+              this.setState({
+                error: result.reason,
+                loading: false,
+                code: null
+              })
+            }
```
Comment (sparrowDom) [inline dapps/marketplace/src/pages/identity/TelegramAttestation.js]: I think there should be an `else` here or a `return inside the if(!result.success)`. Since setState is called twice

Comment (shahthepro) [reply dapps/marketplace/src/pages/identity/TelegramAttestation.js]: Thanks for catching this @sparrowDom. Have fixed that
